#!/bin/sh
while read file
do
    case "$1" in
        "C-d")
            confirm=$(printf "yes\nno" | dmenu -c -l 2 -p "Put to trash?"); [ "$confirm" = "yes" ] && trash-put "$file" ;;
        "C-r")
            convert -rotate 90 "$file" "$file" ;;
        "C-c")
            echo -n "$file" | xclip -selection clipboard ;;
        "C-w")
            feh --bg-fill "$file" -o wal_hooks ;;
    esac
done
