#!/bin/sh
# vim: set foldmethod=marker:

# configuration {{{

# Workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width	  2
bspc config window_gap            10
bspc config split_ratio           0.50
bspc config borderless_monocle    true 
bspc config gapless_monocle       true
bspc config single_monocle        true
bspc config focus_follows_pointer true
# }}}

# colors {{{
bspc config normal_border_color "#000000"
bspc config focused_border_color "#5294e2"
bspc config active_border_color "#e1b700"
bspc config presel_feedback_color "#e345ff"
# }}}

# rules {{{
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a 'MATLAB R2022a - academic use' center=off,border=off
# }}}

# autostart {{{
# system tray
xrdb -merge ~/.Xresources
xres_hooks

nm-applet &
blueman-applet &
~/.config/bspwm/scripts/redshift_startup_script

# start sxhkd
pkill sxhkd && while pgrep sxhkd; do sleep 1; done
ln -sf ~/.config/bspwm/sxhkdrc.bspwm ~/.config/sxhkd/sxhkdrc
sxhkd &

~/.fehbg
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xss-lock --transfer-sleep-lock -- betterlockscreen -l dimblur &
dunst &
picom &
xsetroot -cursor_name left_ptr

# Store bspwm desktop ids and original names for future renaming
bspc query -D > /tmp/bspwm-desktopids
bspc query -D --names > /tmp/bspwm-desktopnames

~/.config/polybar/launch.sh
~/.config/conky/launch.sh

#}}}
